# Generated by Django 3.1.3 on 2021-02-02 05:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('capital', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('dialcode', models.CharField(blank=True, max_length=5, null=True)),
                ('continent', models.CharField(blank=True, max_length=100, null=True)),
                ('tld', models.CharField(blank=True, max_length=5, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iso_639_2', models.CharField(blank=True, max_length=3, null=True)),
                ('iso_639_1', models.CharField(blank=True, max_length=2, null=True)),
                ('english', models.CharField(blank=True, max_length=50, null=True)),
                ('french', models.CharField(blank=True, max_length=50, null=True)),
                ('german', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SIC_Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('utc_offset', models.SmallIntegerField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('uk_region', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Country_Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.language')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_list_rapi.country'),
        ),
    ]
