# Generated by Django 3.1.3 on 2021-02-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_list_rapi', '0002_auto_20210203_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='country_language',
            options={'verbose_name': 'Country Language'},
        ),
        migrations.AlterModelOptions(
            name='countrycurrency',
            options={'verbose_name': 'Country Currencies'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='sic_code',
            options={'verbose_name': 'SIC Code'},
        ),
        migrations.AlterModelOptions(
            name='social_media',
            options={'verbose_name': 'Social Media'},
        ),
    ]
